# Change these first
owner: openvantage # Your GitHub organization or username, where this repository lives
repo: aione-upptime # The name of this repository

sites:
  - name: AiOne
    url: https://www.omnia-ai1.com/
  - name: AiOne API endpoint
    url: https://aebv2k5o9b.execute-api.eu-west-1.amazonaws.com/prod/
    headers:
      - "Content-Type: application/json"
    body: '{}'


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /aione-upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**AiOne Status"
  introMessage: This status page describes the status for AIone and all components
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
